PARAMS_FILE="params.ini"
echo "[DEFAULT]" > $PARAMS_FILE
echo "MongoDbUri = mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/" >> $PARAMS_FILE
echo "Db_name = ${MONGODB_DBNAME}" >> $PARAMS_FILE
echo "Collection_Name = ${MONGODB_COLLECTION_NAME}" >> $PARAMS_FILE
echo "TempDir = ${PYTHON_TEMP_DIR}" >> $PARAMS_FILE
echo "BatchSize = ${PYTHON_BATCH_SIZE}" >> $PARAMS_FILE
echo "[TEST]" >> $PARAMS_FILE
echo "EXPECTED_FIELDS = ${EXPECTED_FIELDS}" >> $PARAMS_FILE
echo "EXPECTED_FIELD_COUNT = ${EXPECTED_FIELD_COUNT}" >> $PARAMS_FILE
echo "[USERS_ROLES]" >> $PARAMS_FILE
RANDOM_PASSWORD1=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13)
echo "READER_USER_NAME = reader_user" >> $PARAMS_FILE
echo "READER_USER_PASSWORD = ${RANDOM_PASSWORD1}" >> $PARAMS_FILE
